"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            "Fruits",
            [
                // 1-4
                {
                    name: "Táo",
                    englishName : "Apple",
                    origin: "Quảng Bắc, Lào Cai",
                    taste: "Ngọt, chua nhẹ",
                    nutrition: "Vitamin C, K, B6; chất xơ",
                    color: "Đỏ, xanh, vàng",
                    season: "Thu", 
                    medical: "Tăng sức đề kháng, giảm nguy cơ mắc bệnh tim",
                    star: 5.0,
                },
                {
                    name: "Chuối",
                    englishName : "Banana",
                    origin: "Đồng bằng sông Cửu Long",
                    taste: "Ngọt",
                    nutrition: "Vitamin C, B6; kali, magie",
                    color: "Vàng",
                    season: "Có sẵn quanh năm", 
                    medical: "Cung cấp năng lượng, giảm căng thẳng",
                    star: 5.0,
                },
                {
                    name: "Đậu",
                    englishName : "Bean",
                    origin: "Nhiều vùng trên cả nước",
                    taste: "Ngọt, béo",
                    nutrition: "Protein, chất xơ, vitamin B",
                    color: "Xanh, vàng, đen",
                    season: "Mùa xuân, hạ", 
                    medical: "Hỗ trợ tiêu hóa, cung cấp năng lượng",
                    star: 5.0,
                },
                {
                    name: "Mướp đắng",
                    englishName : "Bitter Gourd",
                    origin: "Miền Bắc, miền Trung",
                    taste: "Đắng",
                    nutrition: "Vitamin C, A; chất xơ",
                    color: "Xanh",
                    season: "Có sẵn quanh năm", 
                    medical: "Giảm đường huyết, tăng sức đề kháng",
                    star: 5.0,
                },
                // 5-8
                {
                    name: "Bầu",
                    englishName : "Bottle Gourd",
                    origin: "Đồng bằng sông Cửu Long",
                    taste: "Nhạt",
                    nutrition: "Vitamin C, B; chất xơ",
                    color: "Xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Giảm cân, tốt cho hệ tiêu hóa",
                    star: 5.0,
                },
                {
                    name: "Cà tím",
                    englishName : "Brinjal",
                    origin: "Miền Bắc",
                    taste: "Ngọt, thơm",
                    nutrition: "Folate, kali, vitamin C",
                    color: "Tím, trắng, đen",
                    season: "Xuân, hạ",
                    medical: "Hỗ trợ tiêu hóa, giảm nguy cơ bệnh tim",
                    star: 4.5,
                },
                {
                    name: "Súp lơ",
                    englishName : "Broccoli",
                    origin: "Đà Lạt",
                    taste: "Ngọt, cay nhẹ",
                    nutrition: "Vitamin C, K; chất xơ",
                    color: "Xanh",
                    season: "Mùa đông",
                    medical: "Chống ung thư, bảo vệ tim mạch",
                    star: 4.8,
                },
                {
                    name: "Bắp cải",
                    englishName : "Cabbage",
                    origin: "Đà Lạt",
                    taste: "Ngọt, giòn",
                    nutrition: "Vitamin C, K; chất xơ",
                    color: "Xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Chống vi khuẩn, giảm cân",
                    star: 4.7,
                },
                // 9-12
                {
                    name: "Ớt chuông",
                    englishName : "Capsicum",
                    origin: "Đồng bằng sông Cửu Long",
                    taste: "Ngọt, cay nhẹ",
                    nutrition: "Vitamin C, A; chất xơ",
                    color: "Đỏ, vàng, xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Tăng cường hệ miễn dịch, chống oxy hóa",
                    star: 4.9,
                },
                {
                    name: "Cà rốt",
                    englishName : "Carrots",
                    origin: "Đà Lạt",
                    taste: "Ngọt",
                    nutrition: "Vitamin A, K; chất xơ",
                    color: "Đỏ, cam, vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Bảo vệ thị lực, giảm nguy cơ ung thư",
                    star: 4.6,
                },
                {
                    name: "Bông cải",
                    englishName : "Cauliflower",
                    origin: "Đà Lạt",
                    taste: "Ngọt, giòn",
                    nutrition: "Vitamin C, K; chất xơ",
                    color: "Trắng",
                    season: "Mùa đông",
                    medical: "Giảm nguy cơ ung thư, cung cấp năng lượng",
                    star: 4.8,
                },
                {
                    name: "Ớt",
                    englishName : "Chilli",
                    origin: "Đồng bằng sông Cửu Long",
                    taste: "Cay",
                    nutrition: "Vitamin C, A; capsaicin",
                    color: "Đỏ, xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Tăng cường tiêu hóa, giảm đau",
                    star: 4.7,
                },
                //13-16
                {
                    name: "Dừa",
                    englishName : "Coconut",
                    origin: "Miền Nam",
                    taste: "Ngọt",
                    nutrition: "Dầu, kali, mangan",
                    color: "Trắng, xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Tốt cho tim mạch, da và tóc",
                    star: 4.9,
                },
                {
                    name: "Dưa leo",
                    englishName : "Cucumber",
                    origin: "Đồng bằng sông Cửu Long",
                    taste: "Nhạt",
                    nutrition: "Vitamin K, C; nước",
                    color: "Xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Giảm căng thẳng, cung cấp nước cho cơ thể",
                    star: 4.5,
                },
                {
                    name: "Mãng cầu",
                    englishName : "Custard Apple",
                    origin: "Miền Nam",
                    taste: "Ngọt",
                    nutrition: "Vitamin C, B; kali",
                    color: "Xanh, nâu",
                    season: "Có sẵn quanh năm",
                    medical: "Tăng sức đề kháng, giảm mệt mỏi",
                    star: 4.8,
                },
                {
                    name: "Chà là",
                    englishName : "Dates",
                    origin: "Miền Trung, Miền Nam",
                    taste: "Ngọt",
                    nutrition: "Vitamin B, kali, magie",
                    color: "Nâu",
                    season: "Mùa đông",
                    medical: "Tăng cường năng lượng, tốt cho hệ tiêu hóa",
                    star: 4.7,
                },
                //17-20
                {
                    name: "Thanh long",
                    englishName : "Dragon Fruit",
                    origin: "Miền Nam",
                    taste: "Ngọt, giòn",
                    nutrition: "Vitamin C, B; chất xơ",
                    color: "Hồng, xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Bảo vệ tế bào, giảm nguy cơ tiểu đường",
                    star: 4.8,
                },
                {
                    name: "Trứng",
                    englishName : "Egg",
                    origin: "Toàn quốc",
                    taste: "Ngọt, béo",
                    nutrition: "Protein, vitamin B, D",
                    color: "Trắng, vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Xây dựng cơ bắp, tăng cường não bộ",
                    star: 4.6,
                },
                {
                    name: "Tỏi",
                    englishName : "Garlic",
                    origin: "Miền Bắc, Miền Trung",
                    taste: "Cay, thơm",
                    nutrition: "Vitamin C, B6; khoáng chất",
                    color: "Trắng",
                    season: "Có sẵn quanh năm",
                    medical: "Kháng khuẩn, giảm mỡ máu",
                    star: 4.9,
                },
                {
                    name: "Nho",
                    englishName : "Grape",
                    origin: "Ninh Thuận, Lâm Đồng",
                    taste: "Ngọt",
                    nutrition: "Vitamin C, K; chất xơ",
                    color: "Xanh, đỏ, đen",
                    season: "Mùa hè",
                    medical: "Bảo vệ tim mạch, chống oxi hóa",
                    star: 4.7,
                },
                // 21-24
                {
                    name: "Chanh xanh",
                    englishName : "Green Lemon",
                    origin: "Đồng Nai, Vũng Tàu",
                    taste: "Chua",
                    nutrition: "Vitamin C, B; chất xơ",
                    color: "Xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Giảm cân, tăng cường hệ miễn dịch",
                    star: 4.5,
                },
                {
                    name: "Mít",
                    englishName : "Jackfruit",
                    origin: "Miền Nam",
                    taste: "Ngọt, thơm",
                    nutrition: "Vitamin C, B; kali",
                    color: "Vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Tăng cường năng lượng, giảm căng thẳng",
                    star: 4.7,
                },
                {
                    name: "Kiwi",
                    englishName : "Kiwi",
                    origin: "Đà Lạt",
                    taste: "Chua ngọt",
                    nutrition: "Vitamin C, K; chất xơ",
                    color: "Xanh, nâu",
                    season: "Mùa hè",
                    medical: "Bảo vệ tim mạch, tăng cường hệ miễn dịch",
                    star: 4.6,
                },
                {
                    name: "Xoài",
                    englishName : "Mango",
                    origin: "Miền Nam Việt Nam",
                    taste: "Ngọt, có loại hơi chua",
                    nutrition: "Chứa nhiều vitamin C, A, kali",
                    color: "Thay đổi tùy loại, thường là vàng hoặc cam",
                    season: "Xuất hiện chủ yếu vào mùa hè",
                    medical: "Có thể hỗ trợ sức khỏe tim mạch và tăng cường hệ miễn dịch",
                    star: 4.9,
                },
                // 25-28
                {
                    name: "Đậu bắp",
                    englishName : "Okra",
                    origin: "Trồng rộng rãi ở nhiều vùng có khí hậu ấm áp",
                    taste: "Nhẹ, ngọt",
                    nutrition: "Chất xơ, vitamin C, K, và folate",
                    color: "Xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Chứa nhiều chất chống ô nhiễm và có thể hỗ trợ kiểm soát đường huyết",
                    star: 4.6,
                },
                {
                    name: "Hành tây",
                    englishName : "Onion",
                    origin: "Trồng ở khắp mọi nơi",
                    taste: "Cay, có thể ngọt khi chín",
                    nutrition: "Nhiều vitamin C, chất xơ",
                    color: "Trắng, đỏ, vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Có thể giảm nguy cơ bệnh tim và các bệnh ung thư",
                    star: 4.8,
                },
                {
                    name: "Cam",
                    englishName : "Orange",
                    origin: "Miền Bắc và miền Trung Việt Nam",
                    taste: "Ngọt, chua nhẹ",
                    nutrition: "Cao vitamin C, A, kali",
                    color: "Cam",
                    season: "Xuất hiện chủ yếu vào mùa đông",
                    medical: "Tăng cường hệ miễn dịch và duy trì sức khỏe của da",
                    star: 4.7,
                },
                {
                    name: "Dưa lưới",
                    englishName : "Papaya",
                    origin: "Miền Nam Việt Nam",
                    taste: "Ngọt, chua nhẹ",
                    nutrition: "Cao vitamin C, A, enzyme papain",
                    color: "Cam, vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Hỗ trợ tiêu hóa và chứa enzyme có lợi cho dạ dày",
                    star: 4.9,
                },
                // 29-32
                {
                    name: "Lạc",
                    englishName : "Peanut",
                    origin: "Trồng rộng rãi ở nhiều vùng",
                    taste: "Ngọt, béo",
                    nutrition: "Chất béo tốt, protein, vitamin E",
                    color: "Nâu",
                    season: "Có sẵn quanh năm",
                    medical: "Cung cấp năng lượng, hỗ trợ sức khỏe tim mạch",
                    star: 4.5,
                },
                {
                    name: "Dứa",
                    englishName : "Pineapple",
                    origin: "Miền Nam Việt Nam",
                    taste: "Ngọt, có thể chua nhẹ",
                    nutrition: "Cao vitamin C, mangan, chất xơ",
                    color: "Vàng, xanh",
                    season: "Có sẵn quanh năm",
                    medical: "Có chứa enzyme bromelain có thể giúp tiêu hóa",
                    star: 4.7,
                },
                {
                    name: "Lựu",
                    englishName : "Pomegranate",
                    origin: "Miền Bắc Việt Nam",
                    taste: "Ngọt, chua",
                    nutrition: "Cao vitamin C, K, chất chống oxy hóa",
                    color: "Đỏ, hồng",
                    season: "Thường xuất hiện vào mùa thu",
                    medical: "Có chứa chất chống oxy hóa mạnh mẽ",
                    star: 4.8,
                },
                {
                    name: "Khoai tây",
                    englishName : "Potato",
                    origin: "Trồng rộng rãi ở nhiều vùng",
                    taste: "Ngọt, béo",
                    nutrition: "Nhiều carbohydrate, vitamin C, B6",
                    color: "Nâu, trắng, vàng",
                    season: "Có sẵn quanh năm",
                    medical: "Nguồn tốt của vitamin C và kali",
                    star: 4.6,
                },
                // 33-36
                {
                    name: "Bí ngô",
                    englishName : "Pumpkin",
                    origin: "Trồng ở nhiều vùng, đặc biệt là vào mùa thu",
                    taste: "Ngọt, thơm",
                    nutrition: "Cao vitamin A, C, kali",
                    color: "Cam",
                    season: "Thường xuất hiện vào mùa thu",
                    medical: "Chứa nhiều chất chống oxy hóa, hỗ trợ sức khỏe của mắt",
                    star: 4.7,
                },
                {
                    name: "Củ cải",
                    englishName : "Radish",
                    origin: "Trồng rộng rãi ở nhiều vùng",
                    taste: "Có thể cay, giòn",
                    nutrition: "Nhiều vitamin C, chất xơ",
                    color: "Đỏ, trắng",
                    season: "Có sẵn quanh năm",
                    medical: "Cung cấp chất chống ô nhiễm và hỗ trợ tiêu hóa",
                    star: 4.6,
                },
                {
                    name: "Khế",
                    englishName : "Star Fruit",
                    origin: "Miền Nam Việt Nam, đặc biệt là các tỉnh như Bến Tre, Vĩnh Long",
                    taste: "Giữa chua và ngọt, có thể hơi chua",
                    nutrition: "Cao vitamin C, chất xơ",
                    color: "Vàng khi chín",
                    season: "Xuất hiện quanh năm",
                    medical: "Có thể hỗ trợ tiêu hóa và giảm cảm giác căng thẳng",
                    star: 4.8,
                },
                {
                    name: "Dâu",
                    englishName : "Strawberry",
                    origin: "Trồng rộng rãi ở nhiều vùng có khí hậu ôn đới",
                    taste: "Ngọt, có thể hơi chua",
                    nutrition: "Cao vitamin C, mangan, chất xơ",
                    color: "Đỏ",
                    season: "Xuất hiện chủ yếu vào mùa xuân và mùa hè",
                    medical: "Có chứa nhiều chất chống ô nhiễm và chất chống ung thư",
                    star: 4.9,
                },
                // 37-40
                {
                    name: "Khoai lang",
                    englishName : "Sweet Potato",
                    origin: "Trồng rộng rãi ở nhiều vùng",
                    taste: "Ngọt, béo",
                    nutrition: "Cao vitamin A, C, chất xơ",
                    color: "Cam, tím",
                    season: "Có sẵn quanh năm",
                    medical: "Tốt cho sức khỏe tim mạch và kiểm soát đường huyết",
                    star: 4.8,
                },
                {
                    name: "Cà chua",
                    englishName : "Tomato",
                    origin: "Trồng rộng rãi ở nhiều vùng",
                    taste: "Ngọt, có thể chua tùy loại",
                    nutrition: "Cao vitamin C, A, kali, chất xơ",
                    color: "Đỏ",
                    season: "Có sẵn quanh năm",
                    medical: "Chứa lycopene, có thể giảm nguy cơ một số bệnh ung thư",
                    star: 4.7,
                },
                {
                    name: "Dưa hấu",
                    englishName : "Watermelon",
                    origin: "Miền Nam Việt Nam",
                    taste: "Ngọt, mát",
                    nutrition: "Cao vitamin A, C, kali",
                    color: "Đỏ, hồng",
                    season: "Xuất hiện chủ yếu vào mùa hè",
                    medical: "Mát gan, cung cấp nước và khoáng chất",
                    star: 4.9,
                },
                {
                    name: "Nấm trắng",
                    englishName : "White Mushroom",
                    origin: "Trồng rộng rãi, có thể thấy trong nhiều vùng",
                    taste: "Nhẹ, thơm",
                    nutrition: "Cao protein, chất xơ, vitamin D",
                    color: "Trắng",
                    season: "Có sẵn quanh năm",
                    medical: "Tăng cường hệ miễn dịch và hỗ trợ sức khỏe xương",
                    star: 4.8,
                },
            ],
            { batchSize: 40 }
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete("Fruits", null, { batchSize: 40 });
    },
};
